added hospital service unit test
track-your-bed/track-your-bed pull request #40
Opened 2020-03-28 13:17 UTC by urwah1996

2020-03-28 21:31 UTC, turing85 requested changes

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +  @Mock
Don't use `@Mock`. It makes the tests slow.

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +  void shouldThrowNoServiceExcpetionWhenCalculateCapacity() {
`NoSuchHospitalException`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +        .setLon(lon)
Setting attributes is unnecessary since only reference equality is checked.

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +  void shouldThrowNoSuchHospitalExceptionWhenGetHospitalById() {
Each test should have a `@DisplayMessage(...)`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    UUID hospitalId = UUID.randomUUID();
Variable can be `final`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    try {
Please use `assertThrows(...)`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    List<Hospital> hospitals = Arrays.asList(hospital1, hospital2);
Attribute can be `final`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +  @DisplayName("Should call dependencies and return expected result when called.")
Test should be grouped in an inner `@Nested` test class per endpoint.

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    doNothing().when(hospitalRepository).deleteById(any(UUID.class));
Is this mock necessary? Mockito's default behaviour should be to do nothing.

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    verify(hospitalRepository, times(1)).deleteById(any(UUID.class));
- The `UUID` parameter should be verified
- an explicit `times(1)` is not necessary

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    when(hospitalRepository.findById(hospitalId)).thenReturn(Optional.of(hospital));
`findById(any(UUID.class))`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    verify(hospitalDtoMapper, times(0)).entityToDto(hospital);
`verifyNoInteractions(...)`

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    hospital1.setName("hos1");
I would suggest extracting `"hos1"` and `"hos2"` in variables and constructing a `List` of those two varialbes (can be used to verify list size and in `containsInAnyOrder(...)`, for the latter, `toArray()` must be used).

2020-03-28 21:31 UTC, turing85 commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +    final Hospital hospital = getMockHospital();
This is not a mock.

2020-03-29 16:02 UTC, urwah1996 commented
@turing85 please review again. 
Thanks

2020-03-29 16:18 UTC, turing85 approved these changes

2020-03-29 16:38 UTC, atomdampflok commented on backend/src/test/java/de/wirvsvirus/trackyourbed/HospitalServiceTest.java
> +  class updateHospitalTest {
There is some behaviour that also should be tested:
- if fields are not set in the update hospital request, then they are untouched in the entity (Probably having one test per field is a bit too much, but one with `updateHospital=new UpdateHospital()` and nothing else set would be nice)

2020-03-29 17:26 UTC, MichaelSchubertTNG approved these changes

2020-03-29 17:27 UTC, merged